name: test and publish
on: push
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test audit
        run: make test-audit
      - name: test pretty
        run: make test-pretty
      - name: test lint
        run: make test-lint
      - name: test types
        run: make test-types
      - name: test license
        run: make test-license
      - name: test node
        run: cd node && make test
      - name: test react
        run: cd react && make test
  publish-check:
    name: publish check
    needs:
      - test
    runs-on: ubuntu-latest
    outputs:
      is_release: ${{ steps.is_release.outputs.is_release }}
    steps:
      - id: is_release
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+-?[a-z0-9.]*$ ]]; then
              echo ::set-output name=is_release::true
          fi
  build-and-publish:
    name: build + push docker image
    runs-on: ubuntu-latest
    needs:
      - publish-check
      - test
    if: needs.publish-check.outputs.is_release || github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: docker tag
        id: tag
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          echo ::set-output name=image_tag::${IMAGE_TAG}
      - name: docker login
        run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: docker build node
        run: cd node && export DOCKER_IMAGE=opentutor/opentutor-dialog:${{ steps.tag.outputs.image_tag }} && make docker-build
      - name: docker build react
        run: cd react && export DOCKER_IMAGE=opentutor/react:${{ steps.tag.outputs.image_tag }} && make docker-build
      - name: docker tag release as version
        if: needs.publish-check.outputs.is_release == 'true'
        run: |
          docker tag "opentutor/opentutor-dialog:${{ steps.tag.outputs.image_tag }}" "opentutor/opentutor-dialog:${GITHUB_REF#refs/tags/}"
          docker tag "opentutor/react:${{ steps.tag.outputs.image_tag }}" "opentutor/react:${GITHUB_REF#refs/tags/}"
      - name: docker tag main as latest
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag "opentutor/opentutor-dialog:${{ steps.tag.outputs.image_tag }}" "opentutor/opentutor-dialog:latest"
          docker tag "opentutor/react:${{ steps.tag.outputs.image_tag }}" "opentutor/react:latest"
      - name: docker push node
        run: docker push --all-tags opentutor/opentutor-dialog
      - name: docker push react
        run: docker push --all-tags opentutor/react
